export const frasesMotivacionales = [
  "💪 Alimenta tu cuerpo, fortalece tu mente.",
  "🌟 Cada plato es una oportunidad para nutrirte mejor.",
  "🥗 Comer bien es una forma de respetarte a ti mismo.",
  "🔥 La energía que das viene de lo que consumes.",
  "🌈 Come con gratitud, vive con alegría.",
  "🍎 Cuida tu cuerpo, es el único lugar donde tienes que vivir.",
  "✨ Lo que comes hoy, te impulsa mañana.",
  "🌿 Nutrir el cuerpo es honrar la vida.",
  "🌞 Una buena comida es el comienzo de un gran día.",
  "🕊️ Alimentarse bien es una forma de amor propio.",
  "🍽️ La comida sana no es dieta, es estilo de vida.",
  "🌻 Comer bien te llena de energía para soñar más grande.",
  "🧠 Alimenta tu cuerpo y tu mente trabajará mejor.",
  "💚 Cuida lo que comes, cuida lo que piensas.",
  "🌸 Un buen almuerzo, un buen ánimo.",
  "🌞 Empieza el día con gratitud y termina con buena comida.",
  "💧 Hidrátate, respira y agradece.",
  "🍞 No comas menos, come mejor.",
  "🌾 Tu cuerpo merece lo mejor que la tierra ofrece.",
  "🍉 Comer sano también puede ser delicioso.",
  "🌼 Alimentarse bien es una forma de agradecer la vida.",
  "🍇 Los hábitos saludables crean mentes brillantes.",
  "🔥 Tu energía empieza con tu plato.",
  "🧘‍♂️ Alimenta tu equilibrio, no solo tu estómago.",
  "🥑 Comer sano es un acto de amor propio.",
  "🌻 Cada bocado cuenta para sentirte mejor.",
  "🍊 Vive fresco, come natural.",
  "💥 Energía positiva, comida saludable.",
  "🍅 La buena nutrición es el primer paso hacia el éxito.",
  "🌟 Hoy elige alimentos que te hagan sentir bien.",
  "💫 Alimenta tu cuerpo y tu corazón te lo agradecerá.",
  "🌞 Un plato colorido, un día lleno de vida.",
  "🍽️ Siembra hábitos, cosecha bienestar.",
  "💪 Comer sano te da fuerza para tus sueños.",
  "🌈 Llena tu plato de colores, tu día de sonrisas.",
  "🥕 Comer saludable es quererte bien.",
  "🌸 Alimentarte bien es cuidar de ti y de los demás.",
  "🧃 Cada sorbo de agua es vida para tu cuerpo.",
  "🍍 Lo natural siempre sabe mejor.",
  "🍽️ Cuida tu alimentación, es tu combustible diario.",
  "🌿 La salud entra por la boca, pero también por el alma.",
  "🌼 Comer con conciencia es vivir con equilibrio.",
  "🍎 La nutrición es la base del aprendizaje.",
  "💚 Alimenta tu cuerpo para nutrir tus sueños.",
  "🥗 Un cuerpo fuerte sostiene una mente brillante.",
  "🌟 Comer saludable te hace más feliz.",
  "🍉 Cada alimento natural es un regalo para tu salud.",
  "✨ Agradece cada comida, es un acto de amor.",
  "🌿 Lo que siembras en tu plato, florece en tu vida.",
  "🍞 Los pequeños cambios crean grandes resultados.",
  "💧 El agua es tu mejor compañera diaria.",
  "🍇 Come bien, piensa bien, vive bien.",
  "🌈 Tu cuerpo refleja cómo lo alimentas.",
  "🥦 Un plato verde es un corazón contento.",
  "🔥 Tu energía viene de lo que eliges cada día.",
  "🌞 Una sonrisa se alimenta mejor con comida sana.",
  "🍎 Nutrir es una forma de agradecer la vida.",
  "🌼 Alimentarte con amor cambia todo.",
  "💪 La buena comida da fuerza al alma.",
  "🍍 Lo que comes te construye, elige con amor.",
  "🌻 El bienestar empieza en tu plato.",
  "🥗 Cuida tu salud, disfruta tu comida.",
  "🌈 Alimenta tu cuerpo, ilumina tu día.",
  "💚 Comer saludable no es aburrido, es inteligente.",
  "🍉 Una mente sana vive en un cuerpo bien alimentado.",
  "🌸 Nutrirte es una forma de amarte.",
  "🍞 Comer bien es invertir en tu futuro.",
  "🌞 Alimenta tus metas con energía natural.",
  "🔥 La disciplina empieza en lo que comes.",
  "🍽️ Tu cuerpo es tu templo, aliméntalo con respeto.",
  "🌿 Cuida lo que comes, es tu energía vital.",
  "🍎 Comer bien es quererte bien.",
  "🌼 Alimentarse con amor es cuidar la vida.",
  "💪 Cada comida saludable es una victoria.",
  "🌈 Llena tu vida de colores naturales.",
  "🥑 Un corazón feliz empieza con buena comida.",
  "🌟 Alimentarte bien es prepararte para triunfar.",
  "🍉 Hoy elige lo que te hace sentir bien.",
  "✨ El equilibrio comienza en tu plato.",
  "🌿 Cuida tu cuerpo, cuida tu mundo.",
  "🍇 Comer sano es más fácil de lo que crees.",
  "🔥 La salud se cocina a fuego lento.",
  "🌞 Cada almuerzo es una oportunidad de mejorar.",
  "🍽️ Lo que comes influye en cómo te sientes.",
  "🌻 Vive con energía, come con conciencia.",
  "🍎 Elige alimentos que te acerquen a tus metas.",
  "💚 Comer saludable es vivir mejor.",
  "🥗 Cada plato saludable es un paso hacia el éxito.",
  "🌸 Alimentarte con amor te da poder.",
  "🌿 Cuida tu cuerpo, él cuida de ti.",
  "🍍 Come fresco, vive ligero.",
  "🌞 Una buena alimentación ilumina tu día.",
  "🔥 Alimentarte bien es tu superpoder.",
  "🍇 Come bien, piensa en grande.",
  "🌈 Alimenta tu día con color y alegría.",
  "💧 Bebe agua, respira, sonríe.",
  "🍎 Lo que comes te define, elige bien.",
  "🌻 Alimentar tu cuerpo es un acto de sabiduría.",
  "🥗 La comida saludable es la mejor medicina.",
  "🌞 Cada día es una nueva oportunidad para comer mejor.",
  "🍞 Comer bien no es moda, es bienestar.",
  "🌿 Vive sano, come natural.",
  "🔥 La energía que necesitas empieza con lo que comes.",
  "🌈 Un plato lleno de vida te llena de energía.",
  "🍉 Alimentarte bien te hace más fuerte y feliz.",
  "🌼 Cada alimento es una oportunidad para crecer.",
  "💪 Tu bienestar depende de tus hábitos.",
  "🍽️ Comer sano te hace sentir imparable.",
  "🌸 Cuida tu cuerpo, es tu mejor herramienta.",
  "🍎 La buena alimentación nutre tu felicidad.",
  "🌞 Alimenta tu día con alimentos reales.",
  "🌿 Comer bien es cuidar el presente y el futuro.",
  "🔥 Lo saludable también puede ser delicioso.",
  "🥗 Tu cuerpo florece con alimentos naturales.",
  "🍇 Alimentarte bien es invertir en ti mismo.",
  "💧 Una mente clara empieza con un cuerpo sano.",
  "🌻 Siembra salud, cosecha bienestar.",
  "🍎 Lo natural siempre gana.",
  "🌈 Vive ligero, come limpio.",
  "💪 Comer sano es un acto de amor propio.",
  "🌞 Alimentarte bien te da energía para lograrlo todo.",
  "🍍 Cuida tu cuerpo, él te acompaña toda la vida.",
  "🥗 Lo que comes afecta lo que sientes.",
  "🔥 Un cuerpo alimentado con amor rinde más.",
  "🌸 Tu mejor versión comienza con buenos hábitos.",
  "🍉 Alimentarte bien es quererte cada día.",
  "🌿 Vive con equilibrio, come con conciencia.",
  "💚 Comer bien es cuidar de ti y de los que amas.",
  "🍽️ Lo natural es tu mejor medicina.",
  "🌞 Cuida tu alimentación y tu cuerpo te lo agradecerá.",
  "🌈 Alimentarte bien es sembrar bienestar.",
  "🔥 Cada elección saludable te hace más fuerte.",
  "🍎 Vive saludable, vive feliz.",
  "🌿 Alimenta tu cuerpo, calma tu mente.",
  "🍇 Cuida lo que comes, es tu fuente de energía.",
  "🌞 Alimentarte bien te da claridad y fuerza.",
  "🍍 Lo que das a tu cuerpo, te lo devuelve multiplicado.",
  "🌻 Alimentarte con amor es cuidar tu futuro.",
  "💧 Bebe agua, ama, agradece y sonríe.",
  "🍉 Alimentarte bien es cuidar tu luz interior.",
  "🌸 La buena comida alimenta también el alma.",
  "🌈 Lo natural siempre gana.",
  "🍎 Comer sano es una elección de amor propio.",
  "🌞 Cuida tu cuerpo, es tu mejor inversión.",
  "🔥 Alimentarte bien te da poder para cambiar el mundo.",
  "🍽️ Siembra bienestar en cada bocado.",
  "🌿 Comer bien es honrar la vida.",
  "💪 Cada comida saludable es un paso hacia tus metas.",
  "🌈 Lo que comes hoy define cómo te sentirás mañana.",
  "🍇 Alimentarte bien es construir salud.",
  "🌞 Vive con energía, come con alegría.",
  "🥗 La comida saludable nutre cuerpo y mente.",
  "🌸 Cada alimento natural es una bendición.",
  "🍉 Cuida lo que comes, ama lo que haces.",
  "🌻 Alimentarte bien es cuidar tu felicidad.",
  "💚 Vive sano, piensa positivo, come natural.",
  "🍍 Comer bien es la base de un gran día.",
  "🔥 Alimentarte bien es tu mejor inversión.",
  "🌈 Lo natural te llena de vida.",
  "🍎 Alimentarte bien es honrar tu salud.",
  "🌿 Cuida tu cuerpo, respétalo y aliméntalo bien.",
  "🥗 Lo saludable también puede ser delicioso.",
  "🌞 Alimentarte con amor es vivir mejor.",
  "🌻 Cuida lo que pones en tu plato, es lo que te forma.",
  "🍇 Alimentarte bien te hace sentir imparable.",
  "🔥 Vive con energía, come con propósito.",
  "🌿 Alimentarte bien es cuidar tu mente y tu alma.",
  "💧 Tu cuerpo es sabio, aliméntalo con lo mejor.",
  "🍎 Lo natural es siempre la mejor opción.",
  "🌸 Alimentarte con amor es el mejor hábito.",
  "🌞 Comer sano es vivir con plenitud.",
  "🍍 Alimentarte bien te da alegría cada día.",
  "🌻 Cuida tu salud, come con amor.",
  "💚 Alimentarte bien es cuidar tu futuro.",
  "🌈 Cada bocado saludable es un paso hacia tus sueños.",
  "🍉 Lo que comes refleja cómo te amas.",
  "🌿 Alimentarte bien te llena de vida.",
  "🔥 Comer sano te da energía para todo lo que amas.",
  "🌞 Alimentarte con gratitud cambia tu día.",
  "🍎 Vive con amor, come con conciencia.",
  "🌻 Alimentarte bien es el primer paso hacia la felicidad.",
  "💧 Cuida tu cuerpo con cada elección.",
  "🍍 Vive bien, come mejor.",
  "🌸 Alimentarte bien es tu superpoder diario."
];
