export const frases = [
  // 🥗 Alimentación saludable
  "Recuerda beber al menos 8 vasos de agua al día 💧",
  "Incluye frutas y verduras en cada comida 🍎🥦",
  "Come alimentos ricos en fibra para una buena digestión 🌾",
  "Evita las bebidas azucaradas y refrescos 🥤❌",
  "Prefiere proteínas magras como pollo y pescado 🍗🐟",
  "Desayuna siempre para empezar el día con energía 🍳",
  "Incluye grasas saludables como aguacate y nueces 🥑🌰",
  "Modera el consumo de sal en tus comidas 🧂",
  "Come despacio y mastica bien los alimentos 🥄",
  "No te saltes comidas importantes ⏰",
  "Prefiere cocinar al horno o al vapor en lugar de frituras 🍲",
  "Añade superalimentos como quinoa y chia a tu dieta 🌱",
  "Incluye lácteos bajos en grasa para calcio 🥛",
  "Evita comer demasiado antes de dormir 🌙",
  "Consume frutos secos como snack saludable 🥜",
  "Mantén un equilibrio entre carbohidratos, proteínas y grasas ⚖️",
  "Come pescado al menos dos veces por semana 🐠",
  "Prefiere pan integral sobre pan blanco 🍞",
  "Incluye semillas como linaza o girasol en tus ensaladas 🌻",
  "No abuses de la comida rápida 🍔❌",
  "Bebe infusiones naturales como té verde 🍵",
  "Limita el consumo de azúcar refinada 🍬❌",
  "Añade colores variados a tus platos para más nutrientes 🌈",
  "Prefiere frutas de temporada 🍓🍊",
  "Incluye legumbres como lentejas y garbanzos 🥣",
  "Evita comer frente a la televisión 📺❌",
  "Realiza comidas en porciones moderadas 🥗",
  "Haz 5 comidas al día, incluyendo colaciones saludables 🍏",
  "Consume cereales integrales como avena y arroz integral 🌾",
  "Evita exceso de frituras y comida grasosa 🍟❌",
  "Bebe agua antes de sentir sed 💧",
  "Mantén un horario regular para tus comidas ⏰",
  "No uses comida como premio o castigo 🎂❌",
  "Incluye verduras de hojas verdes en tu dieta 🥬",
  "Reduce el consumo de embutidos y carnes procesadas 🥓❌",
  "Prefiere cocinar en casa 🏡",
  "Evita exceso de cafeína ☕❌",
  "Disfruta de tus comidas sin estrés 😊",
  "Come pescado azul por sus Omega 3 🐟",
  "Incluye frutas cítricas por vitamina C 🍋🍊",
  "Prefiere aceite de oliva para tus preparaciones 🫒",
  "Evita el exceso de alcohol 🍷❌",
  "Come alimentos ricos en antioxidantes 🫐",
  "Mantén variedad en tus comidas 🍽️",
  "Incluye sopas y caldos nutritivos 🥣",
  "Modera el consumo de postres 🍰❌",
  "Prefiere agua natural sobre bebidas gaseosas 💧",
  "Incorpora vegetales en snacks y almuerzos 🥕",
  "Come pescado, huevos y legumbres como proteínas alternativas 🥚🐟",
  "Evita exceso de comida ultraprocesada 🍕❌",
  "Planifica tus comidas semanales 📅",
  "Haz ejercicio regularmente para complementar tu alimentación 🏃‍♂️",

  // 💪 Hábitos saludables
  "Duerme al menos 7 horas cada noche 😴",
  "Camina 30 minutos al día 🚶‍♀️",
  "Evita comer con el celular o distracciones 📵",
  "Tómate un tiempo para disfrutar tus comidas 🍽️",
  "Agrega vegetales de colores a cada plato 🌈",
  "Aprende a leer las etiquetas nutricionales 📋",
  "Mantén una postura correcta al comer 🪑",
  "Come por hambre, no por ansiedad 💭",
  "Prepara tus comidas con anticipación 🕓",
  "Incluye más alimentos frescos que procesados 🥗",
  "Modera las porciones, no te excedas 🍽️",
  "Recuerda que comer saludable no es hacer dieta 🚫🍰",
  "Mantén una relación positiva con la comida ❤️",
  "Consume frutas enteras en lugar de jugos 🍊",
  "Reduce el consumo de harinas refinadas 🍞❌",
  "No olvides desayunar antes de salir de casa 🌞",
  "Evita comer en exceso por la noche 🌙",
  "Come sentado y con calma 🪑",
  "Escucha a tu cuerpo cuando te dice que está lleno 🧠",
  "Lleva contigo una botella de agua reutilizable 🚰",
  "Prefiere los alimentos locales y de temporada 🥕",
  "Agrega un toque de limón a tus comidas 🍋",
  "Consume frutas tropicales como piña o mango 🍍🥭",
  "Evita el exceso de salsas y aderezos grasosos 🥫❌",
  "No olvides el poder de una ensalada fresca 🥗",
  "Consume más alimentos naturales que de paquete 🥙",
  "Haz pausas activas durante el día 🧘‍♀️",
  "Evita el estrés, también afecta tu digestión 😌",
  "Consume alimentos ricos en hierro como espinaca o lentejas 🥬🥣",
  "Aumenta el consumo de agua en climas cálidos ☀️💧",
  "Prueba nuevas recetas saludables 👨‍🍳",
  "Evita comer directamente del empaque 📦❌",
  "No olvides lavarte las manos antes de comer ✋🍽️",
  "Evita comer muy rápido ⏳",
  "Prefiere jugos naturales sin azúcar añadida 🍊",
  "No te castigues por un antojo, solo equilibra después ⚖️",
  "Consume yogur natural sin azúcar 🥛",
  "Come más vegetales verdes y menos harinas 🍃",
  "Evita comer por aburrimiento 😴🍪",
  "Combina proteínas con vegetales para una mejor digestión 🥗🍗",

  // 🌞 Motivación y bienestar
  "Tu cuerpo refleja lo que comes 💪",
  "Cada comida saludable es una inversión en ti 🩵",
  "Comer bien también es quererte ❤️",
  "No hay dietas mágicas, solo buenos hábitos 🧘‍♂️",
  "El cambio empieza con un plato equilibrado 🍽️",
  "Hoy puedes empezar a alimentarte mejor 🌟",
  "Una mente sana necesita un cuerpo bien alimentado 🧠🥗",
  "Disfruta de los sabores naturales de la comida 🍎",
  "Tu energía depende de lo que comes ⚡",
  "El agua es tu mejor aliada 💧",
  "Aliméntate bien, vive mejor 🌞",
  "Recuerda: equilibrio, no perfección ⚖️",
  "Cuidar tu alimentación es cuidar tu futuro 🌿",
  "Cada bocado cuenta, hazlo saludable 🍴",
  "Ser saludable también es disfrutar 🍉",
  "Pequeños cambios crean grandes resultados 🌻",
  "Elige alimentos que te hagan sentir bien 💚",
  "No comas menos, come mejor 🍎",
  "La salud entra por la boca 🥗",
  "Tu bienestar es tu prioridad 🌈",
  "Elige conscientemente, come inteligentemente 🧘‍♀️",
  "Comer sano también puede ser delicioso 😋",
  "Cuida tu cuerpo, es el único lugar donde vivirás 🏡",
  "No hay prisa, ve paso a paso 🐢",
  "Un snack saludable puede mejorar tu día 🍇",
  "Tu cuerpo te lo agradecerá 🙌",
  "Haz que tu plato sea tan colorido como tu vida 🌈",
  "Elige alimentos que te den energía, no sueño ⚡😴",
  "Come como si te quisieras 💕",
  "Una buena alimentación mejora tu estado de ánimo 😄",
  "La comida saludable no es aburrida, ¡es creatividad! 🎨",
  "Cuidarte es una forma de amor propio 💚",
  "Cada día es una nueva oportunidad para comer mejor 🌅",
  "Comer saludable también es disfrutar del proceso 🧘‍♂️",
  "Tu salud vale cada elección que haces 🩺",
  "Sonríe, estás cuidando tu cuerpo 😁",
  "El bienestar se construye paso a paso 🚶‍♀️",
  "Ser saludable no es una meta, es un estilo de vida 🧩",
  "Come bien, muévete más, vive feliz 🌞",
  "No hay mejor medicina que una buena alimentación 🍎💊",
  "Tu plato puede ser tu medicina o tu veneno 🍽️⚖️",
  "Elige salud, elige vida 💚",

  // 🌍 Sostenibilidad y conciencia
  "Consume productos locales y apoya a los agricultores 🌾",
  "Evita desperdiciar comida 🍽️❌",
  "Aprovecha las sobras en nuevas recetas ♻️",
  "Reduce el uso de plásticos en tus comidas 🌍",
  "Compra frutas y verduras de temporada 🍅🍇",
  "Cuida el medio ambiente con tus elecciones alimenticias 🌱",
  "Usa envases reutilizables para tus almuerzos 🍱",
  "Elige alimentos sostenibles para cuidar el planeta 🌎",
  "Cocinar en casa también es un acto ecológico 🏡",
  "Recuerda que comer sano también cuida la Tierra 🌿",
];
